---
title: "Final Project Preci"
author: "Teresa Rokos"
date: "10/16/2018"
output: html_document
---

### Medical Expenditure Panel Survey (MEPS) Emergency Room Visits Data
The MEPS is a survey
```{r, echo = FALSE, message=FALSE, error=FALSE, results='hide'}
# MEPS had instructions on how to import their data (which only existed in .dat and .ssp files) into STATA, so I used their provided code in a .do file and generated a .dta file of the data titled "H188E.dta" that I can now read into R.
library(tidyverse)
library(readstata13)
library(knitr)
library(janitor)

emergency_visits_data <- read.dta13("H188E.dta", generate.factors = T, nonint.factors = TRUE)
glimpse(emergency_visits_data)
```

The variables included are:
``` {r, echo = FALSE}
names(emergency_visits_data) <- c("DWELLING UNIT ID",
  "PERSON NUMBER",
  "PERSON ID (DUID + PID)",
  "EVENT ID",
  "EVENT ROUND NUMBER",
  "EVENT ID FOR CORRESPONDING HOSPITAL STAY",
  "FLAT FEE ID",
  "PANEL NUMBER",
  "MPC DATA FLAG",
  "EVENT DATE - YEAR",
  "EVENT DATE - MONTH",
  "BEST CATEGORY FOR CARE P RECV ON VST DT",
  "THIS VST RELATED TO SPEC CONDITION",
  "THIS VISIT DID P HAVE LAB TESTS",
  "THIS VISIT DID P HAVE SONOGRAM OR ULTRSD",
  "THIS VISIT DID P HAVE X-RAYS",
  "THIS VISIT DID P HAVE A MAMMOGRAM",
  "THIS VISIT DID P HAVE AN MRI/CATSCAN",
  "THIS VISIT DID P HAVE AN EKG OR ECG",
  "THIS VISIT DID P HAVE AN EEG",
  "THIS VISIT DID P RECEIVE A VACCINATION",
  "THIS VISIT DID P RECEIVE ANESTHESIA",
  "THIS VISIT DID P HAVE A THROAT SWAB",
  "THIS VISIT DID P HAVE OTH DIAG TEST/EXAM",
  "WAS SURG PROC PERFORMED ON P THIS VISIT",
  "ANY MEDICINE PRESCRIBED FOR P THIS VISIT",
  "MODIFIED CLINICAL CLASSIFICATION CODE",
  "MODIFIED CLINICAL CLASSIFICATION CODE",
  "MODIFIED CLINICAL CLASSIFICATION CODE",
  "MODIFIED CLINICAL CLASSIFICATION CODE",
  "FLAT FEE BUNDLE",
  "TOTAL # OF VISITS IN FF BEFORE 2016",
  "TOT EXP FOR EVENT (ERFXP16X + ERDXP16X)",
  "TOTAL CHG FOR EVENT (ERFTC16X+ERDTC16X)",
  "FACILITY AMT PD, FAMILY (IMPUTED)",
  "FACILITY AMT PD, MEDICARE (IMPUTED)",
  "FACILITY AMT PD, MEDICAID (IMPUTED)",
  "FACILITY AMT PD, PRIV INSUR (IMPUTED)",
  "FAC AMT PD,VETERANS/CHAMPVA(IMPUTED)",
  "FACILITY AMT PD,TRICARE(IMPUTED)",
  "FACILITY AMT PD, OTH FEDERAL (IMPUTED)",
  "FACILITY AMT PD, STATE/LOC GOV (IMPUTED)",
  "FACILITY AMT PD, WORKERS COMP (IMPUTED)",
  "FACILITY AMT PD, OTH PRIV (IMPUTED)",
  "FACILITY AMT PD, OTH PUB (IMPUTED)",
  "FACILITY AMT PD, OTH INSUR (IMPUTED)",
  "FACILITY SUM PAYMENTS ERFSF16X-ERFOT16X",
  "TOTAL FACILITY CHARGE (IMPUTED)",
  "DOCTOR AMOUNT PAID, FAMILY (IMPUTED)",
  "DOCTOR AMOUNT PD, MEDICARE (IMPUTED)",
  "DOCTOR AMOUNT PAID, MEDICAID (IMPUTED)",
  "DOCTOR AMT PD, PRIV INSUR (IMPUTED)",
  "DR AMT PD,VETERANS/CHAMPVA(IMPUTED)",
  "DOCTOR AMT PD,TRICARE(IMPUTED)",
  "DOCTOR AMT PAID, OTH FEDERAL (IMPUTED)",
  "DOCTOR AMT PD, STATE/LOC GOV (IMPUTED)",
  "DOCTOR AMOUNT PD, WORKERS COMP (IMPUTED)",
  "DOCTOR AMT PD, OTH PRIVATE (IMPUTED)",
  "DOCTOR AMT PD, OTH PUB (IMPUTED)",
  "DOCTOR AMT PD, OTH INSUR (IMPUTED)",
  "DOCTOR SUM PAYMENTS ERDSF16X - ERDOT16X",
  "TOTAL DOCTOR CHARGE (IMPUTED)",
  "IMPUTATION STATUS",
  "EXPENDITURE FILE PERSON WEIGHT, 2016",
  "VARIANCE ESTIMATION STRATUM, 2016",
  "VARIANCE ESTIMATION PSU, 2016")
variables <- list(names(emergency_visits_data))

kable(variables, col.names = "Variable Names")
```

``` {r, echo = FALSE, results='hide'}
emergency_visits_data <- clean_names(emergency_visits_data, case = c("snake"))
glimpse(emergency_visits_data)
```

